[virtualenvs]
cache-dir = "."
in-project = true
create = true
[repositories]

#incase pypi is inaccessible
[repositories.fpho]
url = "https://files.pythonhosted.org"
[certificates.PyPI]
cert = false
[certificates.fpho]
cert = false
